const INDEX_BANNER = "<!-- AUTO-GENERATED by grove. Do not edit. Run `grove render` to refresh. -->"

function render_index(st::State)::String
    io = IOBuffer()
    println(io, INDEX_BANNER)
    println(io)
    println(io, "# Development dashboard")
    println(io)
    render_goals!(io, st)
    render_work!(io, st)
    render_decisions!(io, st)
    render_questions!(io, st)
    render_assumptions!(io, st)
    render_retros!(io, st)
    render_artifacts!(io, st)
    render_graph!(io, st)
    String(take!(io))
end

function question_targets(st::State, q::Node)::Vector{String}
    sort!(collect(Set([e.to for e in st.edges if e.label === :asks && e.from == q.id])))
end

function assumption_tests(st::State, b::Node)::Vector{String}
    sort!(collect(Set([e.to for e in st.edges if e.label === :tests && e.from == b.id])))
end

function assumption_targets(st::State, b::Node)::Vector{String}
    sort!(collect(Set([e.to for e in st.edges if e.label === :targets && e.from == b.id])))
end

function decision_supersedes(st::State, d::Node)::Vector{String}
    sort!(collect(Set([e.to for e in st.edges if e.label === :supersedes && e.from == d.id])))
end

function render_goals!(io, st)
    rows = listnodes(st, :g)
    isempty(rows) && return
    println(io, "## Goals")
    println(io)
    println(io, "| ID | Outcome | Fitness function | Status |")
    println(io, "| --- | --- | --- | --- |")
    for n in rows
        f = goal_fitness_table_cell(n)
        println(io, "| ", n.id, " | ", n.title, " | ", f, " | ", n.status, " |")
    end
    println(io)
end

function render_work!(io, st)
    rows = listnodes(st, :w)
    isempty(rows) && return
    cp = Set(critical_path(st))
    println(io, "## Work items")
    println(io)
    println(io, "| ID | Type | Title | Goals | Cynefin | DoR | Status | Critical |")
    println(io, "| --- | --- | --- | --- | --- | --- | --- | --- |")
    for n in rows
        gs = join(get(n.fields, :goals, String[]), ", ")
        do_r = dor(st, n) ? "⊤" : "⊥"
        crit = n.id in cp ? "★" : ""
        println(io, "| ", n.id, " | ", n.type, " | ", n.title, " | ", gs, " | ",
                n.cynefin, " | ", do_r, " | ", n.status, " | ", crit, " |")
    end
    println(io)
end

function render_decisions!(io, st)
    rows = listnodes(st, :d)
    isempty(rows) && return
    println(io, "## Decisions")
    println(io)
    println(io, "| ID | Title | Status | Supersedes |")
    println(io, "| --- | --- | --- | --- |")
    for n in rows
        sup = join(decision_supersedes(st, n), ", ")
        println(io, "| ", n.id, " | ", n.title, " | ", n.status, " | ", sup, " |")
    end
    println(io)
end

function render_questions!(io, st)
    rows = listnodes(st, :q)
    isempty(rows) && return
    println(io, "## Open questions")
    println(io)
    println(io, "| ID | Question | Cynefin | Targets | Status |")
    println(io, "| --- | --- | --- | --- | --- |")
    for n in rows
        t = join(question_targets(st, n), ", ")
        println(io, "| ", n.id, " | ", n.title, " | ", n.cynefin, " | ", t, " | ", n.status, " |")
    end
    println(io)
end

function render_assumptions!(io, st)
    rows = listnodes(st, :b)
    isempty(rows) && return
    println(io, "## Assumptions")
    println(io)
    println(io, "| ID | Assumption | Tests | Targets | Status |")
    println(io, "| --- | --- | --- | --- | --- |")
    for n in rows
        ts = join(assumption_tests(st, n), ", ")
        tg = join(assumption_targets(st, n), ", ")
        println(io, "| ", n.id, " | ", n.title, " | ", ts, " | ", tg, " | ", n.status, " |")
    end
    println(io)
end

function render_retros!(io, st)
    rows = listnodes(st, :r)
    isempty(rows) && return
    println(io, "## Retrospectives")
    println(io)
    println(io, "| ID | Goal | Date | Status |")
    println(io, "| --- | --- | --- | --- |")
    for n in rows
        g = get(n.attrs, "goal", "")
        d = get(n.attrs, "date", "")
        println(io, "| ", n.id, " | ", g, " | ", d, " | ", n.status, " |")
    end
    println(io)
end

function artifact_causes_work(st::State, a::Node)::Vector{String}
    out = Set{String}()
    for e in st.edges
        e.label === :causes || continue
        e.from == a.id || continue
        push!(out, e.to)
    end
    sort!(collect(out))
end

function artifact_themed_work(st::State, a::Node)::Vector{String}
    aid = String(a.id)
    sort!([w.id for w in listnodes(st, :w) if strip(string(get(w.fields, :theme, ""))) == aid])
end

function render_artifacts!(io, st)
    rows = listnodes(st, :a)
    isempty(rows) && return
    println(io, "## Artifacts")
    println(io)
    println(io, "| ID | Title | Status | Causes work | Themed work |")
    println(io, "| --- | --- | --- | --- | --- |")
    for n in rows
        cw = join(artifact_causes_work(st, n), ", ")
        tw = join(artifact_themed_work(st, n), ", ")
        println(io, "| ", n.id, " | ", n.title, " | ", n.status, " | ",
                isempty(cw) ? "—" : cw, " | ", isempty(tw) ? "—" : tw, " |")
    end
    println(io)
end

function node_class(n::Node)::String
    if n.kind === :g; return "goal"
    elseif n.kind === :d; return "decision"
    elseif n.kind === :q; return "question"
    elseif n.kind === :b; return "assumption"
    elseif n.kind === :r; return "retro"
    elseif n.kind === :a; return "theme"
    elseif n.kind === :w
        if n.type === :spike; return "spike"
        elseif n.status === :done || n.status === :archived; return "done"
        elseif n.status === :progress; return "progress"
        elseif n.status === :ready; return "ready"
        elseif n.status === :rejected; return "rejected"
        else; return "feature"
        end
    end
    "feature"
end

function render_graph!(io, st)
    println(io, "## Dependency graph")
    println(io)
    println(io, "```mermaid")
    println(io, "graph TD")
    cp = Set(critical_path(st))
    ids = String[]
    for kind in NODE_KINDS
        for n in listnodes(st, kind)
            push!(ids, n.id)
            label = replace(n.title, '"' => "'")
            cls = node_class(n)
            line = "  $(mermaid_safe(n.id))[\"$(n.id): $(label)\"]:::$(cls)"
            n.id in cp && (line *= ",critical")
            println(io, line)
        end
    end
    for e in sort(st.edges; by=e -> (e.from, String(e.label), e.to))
        haskey(st.nodes, e.from) && haskey(st.nodes, e.to) || continue
        println(io, mermaid_edge_line(e.from, e.to, e.label))
    end
    if !isempty(cp)
        cp_ids = sort!(collect(cp))
        println(io, "  class ", join(mermaid_safe.(cp_ids), ","), " critical")
    end
    println(io, """
  classDef goal fill:#1e3a5f,color:#fff
  classDef theme fill:#2a4a3a,color:#fff
  classDef decision fill:#5a4a1e,color:#fff
  classDef question fill:#5a3a1e,color:#fff
  classDef assumption fill:#4a2d5a,color:#fff
  classDef spike fill:#3a3a5a,color:#fff
  classDef feature fill:#1e4a4a,color:#fff
  classDef ready fill:#2d5a27,color:#fff
  classDef progress fill:#3a4a6a,color:#fff,stroke:#fff,stroke-width:2px
  classDef done fill:#2d5a27,color:#fff,stroke:#fff,stroke-width:2px
  classDef rejected fill:#5a5a5a,color:#fff
  classDef retro fill:#1a3d3d,color:#fff,stroke:#7fd0d0,stroke-width:2px
  classDef critical stroke:#ff0,stroke-width:3px""")
    println(io, "```")
    println(io)
end

mermaid_safe(id::AbstractString) = replace(String(id), '-' => '_')

"""Mermaid `graph TD` link: thick `blocks`, dotted `targets`, plain labeled arrow for others (e.g. `produces`)."""
function mermaid_edge_line(from::AbstractString, to::AbstractString, label::Symbol)::String
    f = mermaid_safe(from)
    t = mermaid_safe(to)
    s = String(label)
    if label === :blocks
        return string("  ", f, " ==>|", s, "| ", t)
    elseif label === :targets
        return string("  ", f, " -.->|", s, "| ", t)
    else
        return string("  ", f, " -->|", s, "| ", t)
    end
end

function write_index(path::AbstractString, st::State)
    atomic_write_same_dir!(path, render_index(st))
end
